version: "3.9"

services:
  musicon-app:
    build: .
    container_name: musicon-app
    volumes:
      - .:/app
    command: streamlit run py.py --server.address=0.0.0.0 --server.port=8501
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: musicon-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/etc/nginx/html
      - ./certs:/etc/letsencrypt
    depends_on:
      - musicon-app
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx/html:/etc/nginx/html
    entrypoint: >
      sh -c "
        trap exit TERM;
        while :; do
          certbot renew --webroot -w /etc/nginx/html --quiet;
          sleep 12h & wait $${!};
        done
      "
